library(annotate)
library("biomaRt")
library(DOSE)
library("enrichplot")
library(gage)
library(gageData)
library("genefilter")
library(pathfindR)
library(pathview)
library(ReactomePA)
library(clusterProfiler)
#library(annovarR)

library(vcfR)

library(org.Hs.eg.db)
library(org.Mm.eg.db)

data(kegg.sets.hs)
data(go.sets.hs)
data(carta.hs)
data(sigmet.idx.hs)
data(go.subs.hs)

data(kegg.sets.mm)
data(go.sets.mm)
data(sigmet.idx.mm)
data(go.subs.mm)

data(kegg.sets.rn)
data(go.sets.rn)
data(sigmet.idx.rn)
data(go.subs.rn)

data(kegg.sets.sc)
data(go.sets.sc)
data(sigmet.idx.sc)
data(go.subs.sc)
