library(org.Mm.eg.db)
library(org.Mm.eg.db)

library(pathview)
library(pathfindR)
library(ReactomePA)
library(enrichplot)
library(DOSE)

library(gage)
library(gageData)
data(kegg.sets.hs)
data(go.sets.hs)
data(carta.hs)
data(sigmet.idx.hs)
data(go.subs.hs)

data(kegg.sets.mm)
data(go.sets.mm)
data(sigmet.idx.mm)
data(go.subs.mm)

data(kegg.sets.rn)
data(go.sets.rn)
data(sigmet.idx.rn)
data(go.subs.rn)

data(kegg.sets.sc)
data(go.sets.sc)
data(sigmet.idx.sc)
data(go.subs.sc)
